version: '2.1'
services:
  servicevalsonarqube:
    image: sonarqube
    healthcheck:
      test: ["CMD", "curl", "-f", "http://servicevalsonarqube:9000"]
      interval: 5s
      timeout: 5s
      retries: 2
    ports:
      - "9000:9000"
  servicevaljenkins:
    build: .
    volumes:
      - ./ansible-cfg:/var/jenkins_home/ansible-cfg
      - ./jenkins_home:/var/jenkins_home
      - ~/.ssh/id_rsa:/home/jenkins/.ssh/id_rsa
      - ~/.ssh/id_rsa.pub:/home/jenkins/.ssh/id_rsa.puba
      - ~/.ssh/id_rsa:/var/jenkins_home/.ssh/id_rsa
    ports:
      - "8080:8080"
    depends_on:
      servicevalsonarqube:
         condition: service_healthy
  
  
